billwright/rattlesnake_ramble

- .gitignore
- app/models/race_edition.rb
I'm pretty sure the RaceEdition model is not intended to have many race_editions, but I could be missing something. Also updated .gitignore to ignore RubyMine (.idea) files.
> Remove circular association

- Gemfile
- Gemfile.lock
- app/models/race.rb
- app/models/racer.rb
- spec/models/race_spec.rb
- spec/models/racer_spec.rb
- spec/spec_helper.rb
This will ensure leading and trailing spaces are stripped from strings before saving to the database. Installation of the gem affects only future records, but we can use it to take care of existing trailing spaces as well. After installation, we can run a couple of lines from the console to strip spaces from existing records, like this: 
`Racer.find_each(&:save)`
`Race.find_each(&:save)`
The gem is triggered by a before_save callback, so the act of saving existing records will perform the strip.
> Add strip_attributes gem

- app/models/concerns/birth_date_validator.rb
- app/models/race_entry.rb
- app/models/racer.rb
- spec/factories/racer.rb
- spec/models/race_entry_spec.rb
- spec/models/racer_spec.rb
- spec/presenters/race_edition_presenter_spec.rb
Fixes the problem of two-digit birthdates being interpreted as being xx years from 0 (for example, 3/15/08 being interpreted as March 15, 0008). Addresses #39.
This PR implements a before_save callback that interprets two-digit year dates as being in the 1900s or 2000s, as appropriate.
> Validate birthdates

- app/models/racer.rb
- spec/models/racer_spec.rb
This avoids the problem of having a two-digit year invalidated before it can be fixed by the callback.
> Change Racer before_save callbacks to before_validation callbacks.

- app/controllers/race_editions_controller.rb
- app/models/race_edition.rb
- app/services/ost/translate_race_entry.rb
- app/views/race_editions/_form.html.erb
- db/migrate/20190913124555_add_offsets_to_race_editions.rb
- db/schema.rb
- spec/models/race_edition_spec.rb
- spec/services/ost/translate_race_entry_spec.rb
When exporting data to OST, there is currently not a way to set scheduled start times for male as opposed to female racers. 
This PR adds `male_offset` and `female_offset` attributes to the RaceEdition model, allowing the user to set an offset for male and female runners. The attributes default to 0.
For example, if the scheduled race will have men starting at 7:45 and women at 8:00, we would create the event and add a 15-minute female offset. When racers are imported into OST, start times will then be accurately reflected.
> Add start time offsets

- Procfile
Currently, when code is deployed to Heroku, we have to remember to run migrations or we end up with errors in production. 
This MR creates a basic Procfile that specifies Puma server settings (pointing to the existing `config/puma.rb`) and adds `rake db:migrate` to the release phase.
Heroku Procfile information can be found here: https://devcenter.heroku.com/articles/procfile
Information about the Heroku Release Phase is here: https://devcenter.heroku.com/articles/release-phase
> Add Procfile to run migrations on deploys

- app/controllers/race_editions_controller.rb
- app/views/race_editions/_form.html.erb
- app/views/race_editions/edit.html.erb
- app/views/races/show.html.erb
Currently, the race edition form is misleading because it contains a "Name" field. A race edition name is not a persisted attribute and cannot be changed. It is a computed field built from the associated race and the date of the race edition. 
The form was always a bit confusing because it included "name" as a label in the form. https://github.com/billwright/rattlesnake_ramble/pull/45 made matters worse by including a "name" field to match the label. This PR corrects the problem by removing "name" entirely from the race editions form and putting it in the title of the race_editions/edit view.
Also, a new race edition cannot be created through the forms because some required parameters are not permitted params in the race editions controller. Also, when a new race edition form is accessed …
> Fix the Race Editions form

- app/services/ost/get_token.rb
- app/services/ost/post_entries.rb
- config/initializers/01_ramble_config.rb
- spec/services/ost/get_token_spec.rb
- spec/services/ost/post_entries_spec.rb
This should fix tests that are failing as a result of having incomplete environment variables, including in the GitLab CI pipeline.
First step in addressing #70
> Move environment variables to config and properly stub specs

- db/migrate/20200904043442_add_scheduled_start_time_to_race_entries.rb
- db/schema.rb
Database migration to add the `scheduled_start_times` column to the `race_entries` table.
Addresses a portion of #64
> Migration to add scheduled_start_time to race_entries table

- app/controllers/race_editions_controller.rb
- app/models/concerns/time_zonable.rb
- app/models/race_edition.rb
- app/views/race_editions/_form.html.erb
- config/initializers/01_ramble_config.rb
- spec/models/race_edition_spec.rb
Introduces a `TimeZonable` module, which provides `_local` extensions to specified attributes. Using the `_local` extensions, this module converts time strings into the home time zone for the including class and uses a default date if provided by the including class. 
Makes the Race Edition `default_start_time_female` and `default_start_time_male` attributes zonable.
Provides a UI for setting default start times for those attributes.
Addresses a portion of #64
> Race Edition default start times

- db/migrate/20200906161043_devise_create_users.rb
- db/schema.rb
Fixes a faulty migration. It should be OK to edit this migration directly, because it hasn't been run in production.
> Remove index from users table

- app/controllers/race_editions_controller.rb
- app/controllers/race_entries_controller.rb
- app/controllers/racers_controller.rb
- app/controllers/races_controller.rb
- app/helpers/application_helper.rb
- app/models/race_edition.rb
- app/models/user.rb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_navigation.html.erb
Currently we have a `users` table in place and the Devise gem installed, but we are not authenticating the user anywhere.
This MR introduces authentication in the controllers for the four core models: Races, Racers, Race Editions, and Race Entries.
Also, the header is getting a bit crowded, so this MR introduces dropdown menus to tighten things up a bit.
Finally, the hardcoded race edition slugs in the navigation header make it difficult to test the UI when developing locally. That also requires the slugs to be updated each year by manually pushing up a change. This MR makes those slugs dynamic by testing for the most recent kids and non-kids edition.
Addresses a portion of #23
> Implement admin login with Devise

- app/views/race_editions/enter.html.erb
- app/views/race_entries/_entries.html.erb
- db/migrate/20200913140801_remove_default_from_racer_gender.rb
- db/schema.rb
We had a couple of instances of women entering themselves as men because the gender is set to Male by default. 
This PR proposes to remove the default and require an entrant to pick a gender from the dropdown menu, reducing the chances of this problem happening in the future.
> Remove default gender from Racers

- config/environments/development.rb
- config/environments/test.rb
- db/seeds.rb
We're getting the following deprecation warning in development and test environments:
```
DEPRECATION WARNING: Leaving `ActiveRecord::ConnectionAdapters::SQLite3Adapter.represent_boolean_as_integer`
set to false is deprecated. SQLite databases have used 't' and 'f' to serialize
boolean values and must have old data converted to 1 and 0 (its native boolean
serialization) before setting this flag to true. Conversion can be accomplished
by setting up a rake task which runs
ExampleModel.where("boolean_column = 't'").update_all(boolean_column: 1)
ExampleModel.where("boolean_column = 'f'").update_all(boolean_column: 0)
for all models and all boolean columns, after which the flag must be set to
true by adding the following to your application.rb file: …
```
> SQLite boolean fix

- Gemfile
- Gemfile.lock
- app/models/racer.rb
- spec/models/racer_spec.rb
- spec/spec_helper.rb
Uses the new `capitalize_attributes` gem instead of custom `fix_lazy_capitalization` callback in the Racer model.
> Swap out fix_lazy_capitalization callback in favor of capitalize_attributes gem

- README.md
Bringing the README file up to date with the Ruby and Rails versions we're currently using (2.7 and 6.0, respectively).
This also serves the purpose of triggering a redeploy to address #108.
> Updating versions in the README

- app/views/race_editions/show.html.erb
Currently, we are seeing two admin-only buttons on the Entrants list view. The buttons take the user to a login screen, so this is not a security problem. But it's a bit confusing to show those buttons at all to visitors.
This PR hides both of those buttons from visitors.
> Hide admin buttons from visitors

- app/models/race.rb
- app/models/race_edition.rb
- db/migrate/20220807134041_create_friendly_id_slugs.rb
- db/schema.rb
- lib/tasks/friendly_id/update_slugs.rake
To enable history tracking for friendly_id slugs, we need to add a database table. 
This PR includes the standard migration to add a `friendly_id_slugs` table. It also includes a rake task that will add existing slugs to the table.
Addresses #135
> History for friendly_id slugs

- app/controllers/application_controller.rb
- app/controllers/race_editions_controller.rb
- app/controllers/races_controller.rb
- app/models/race.rb
- app/models/race_edition.rb
- spec/presenters/race_edition_presenter_spec.rb
Currently, when a Race or Race Edition is changes, the slug does not change. Also, when a user requests a URL with an older slug, the user is shown the proper page but is not redirected to the new URL.
This PR adds automatic slug changes and also redirects when an older URL is requested.
In addition, the Race Edition slugs were getting quite long. This PR changes from using `race.name` + `date` to using `race.short_name` + `date`. 
We should run the `friendly_id:update_all_slugs` rake task after this PR is deployed.
> Automatically change slugs and redirect

- app/controllers/enter_controller.rb
- app/controllers/pages_controller.rb
Pushing up the Rails 6.1 configs (https://github.com/billwright/rattlesnake_ramble/pull/140) resulted in the app crashing with a zeitwerk error:
```
2022-09-05T23:51:16.497569+00:00 app[web.1]: Puma starting in single mode...
2022-09-05T23:51:16.497587+00:00 app[web.1]: * Puma version: 5.6.4 (ruby 2.7.6-p219) ("Birdie's Version")
2022-09-05T23:51:16.497587+00:00 app[web.1]: *  Min threads: 5
2022-09-05T23:51:16.497587+00:00 app[web.1]: *  Max threads: 5
2022-09-05T23:51:16.497587+00:00 app[web.1]: *  Environment: production
2022-09-05T23:51:16.497588+00:00 app[web.1]: *          PID: 4
2022-09-05T23:51:19.569447+00:00 app[web.1]: ! Unable to load application: Zeitwerk::NameError: expected file /app/app/controllers/enter_controller.rb to define constant EnterController, but didn't …
```
> Remove the enter_controller file (needed for zeitwerk compatibility)

- .github/workflows/ruby.yml
- README.md
We are rebuilding the bundle with every CI pipeline run. This PR enables bundle caching, which should take a few minutes off most runs.
> Streamline CI pipeline with bundle caching

- Gemfile
- Gemfile.lock
By including these additional gems, I believe we can get running on Heroku with Ruby 3.1 without upgrading (yet) to Rails 7.
> Include smtp-imap and smtp-pop in Gemfile

- app/controllers/race_editions_controller.rb
- app/views/race_editions/index.json.jbuilder
- config/routes.rb
In order to determine which race editions should be connected to OST, we need a JSON endpoint that returns race editions.
This PR adds that endpoint and protects it with authentication via query params, the same as for the JSON show endpoint.
> Add a JSON index endpoint for Race Editions

- app/views/race_editions/show.json.jbuilder
Currently, we are not sending default male and female scheduled start times on race entries in the JSON race edition view.
This PR adds those default times.
> Put default start times on race entries in the JSON view

- app/controllers/pages_controller.rb
- app/views/pages/enter.html.erb
- config/routes.rb
This PR removes the legacy `PagesController#enter` action, route, and view, because it has been replaced by the newer `RaceEditionsController#enter` action.
Resolves #143
> Remove the unused PagesController#enter action with related route and view

- config/database.yml
We are seeing
`ActiveRecord::ConnectionNotEstablished: fe_sendauth: no password supplied`
when running postgres on some local installations. This should fix the problem.
> Fix postgres config file

- app/controllers/racers_controller.rb
- app/views/race_entries/_form.html.erb
- app/views/racers/_form.html.erb
- app/views/racers/edit.html.erb
In #190, we suggested a Racer's birthdate should be editable from the Race Entry page. Because Racer is the parent record of the related Race Entry, this is not easily done.
This PR instead adds a handy link to reach the Racers Edit page directly from the Race Entries Edit page. It also stores a `return_to` param, which allows the Racer Update action to return the user to the Race Entries Edit page seamlessly.
> Link to Edit Racer

- app/views/race_editions/show.html.erb
Added an "Unpaid Emails" button to the Entrants page.  
It links to the existing Racer Emails view filtered for unpaid entries.
> Add Unpaid Emails button on Entrants page linking to unpaid racer emails

- Gemfile.lock
- app/controllers/race_editions_controller.rb
- app/views/race_editions/race_entries.html.erb
- app/views/race_editions/show.html.erb
- config/routes.rb
- Refactored race registration to create RaceEntry only after successful PayPal return
- Added payment_success and payment_cancelled actions to RaceEditionsController
- Updated routes for new callbacks
- Updated race_entries and show views accordingly
- Keeps old flow (successful_entry/cancelled_payment on RaceEntry) intact for backward compatibility
> feat: implement pay-first registration flow

- app/controllers/race_editions_controller.rb
- config/secrets.yml
Fixes the PayPal callback logic and updates `app_host` to HTTPS to ensure RaceEntry creation after successful payments.
In production, paid entrants weren’t appearing because PayPal was returning to an insecure HTTP endpoint. The `payment_success` route never triggered, so no RaceEntry was created.
- Corrected PayPal `return` URL to include `?racer_id=...&merchandise_size=...`
- Updated production `app_host` to `https://www.rattlesnakeramble.org`
- Verified locally that the payment_success flow now creates RaceEntry (paid: true)
- Paid racers now appear immediately in entrants list.
- No need to revert pay-first flow; production will work once redeployed with HTTPS host.
> Fix PayPal return URL and update production app_host to HTTPS
